import org.json.simple.parser.JSONParser;
import java.io.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.json.simple.parser.ParseException;
import org.json.simple.JSONObject;
import org.json.simple.JSONArray;


/**
 * <b>ForgotPassword</b>
 * <p>
 * The ForgotPassword Page class uses the JFrame package to reset user's password.
 * </p>
 * @author Team 12
 */

public class ForgotPassword extends javax.swing.JFrame {
    
    /*
    * Instance variables
    */
    
    User user;
    Admin admin;
    UserDatabase usrDb;
    SystemDatabase sysDb;
    String getUsername;
    String getPassword;
    JSONParser parser;

    
    /**
     * Creates new form LandingPage
     */
    
    public ForgotPassword() {
        initComponents();
        this.sysDb = new SystemDatabase();
        this.usrDb = new UserDatabase();
        this.parser = new JSONParser();
        setIcons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forgotUsername = new javax.swing.JLabel();
        enterForgotUsername = new javax.swing.JTextField();
        forgotSecurity = new javax.swing.JLabel();
        selectSecurityQuestion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        enterSecurityAnswer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        enterNewPassword = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forgotUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        forgotUsername.setForeground(new java.awt.Color(255, 255, 255));
        forgotUsername.setText("Username:");
        getContentPane().add(forgotUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        enterForgotUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterForgotUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(enterForgotUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 190, -1));

        forgotSecurity.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        forgotSecurity.setForeground(new java.awt.Color(255, 255, 255));
        forgotSecurity.setText("Security Question:");
        getContentPane().add(forgotSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        selectSecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class Code" }));
        getContentPane().add(selectSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 190, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Answer:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));
        getContentPane().add(enterSecurityAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 190, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Your New Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        enterNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterNewPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(enterNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, -1));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, -1, -1));

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon("/Users/RexGu/Documents/UWO 2022-2023/CS2212/FInal Project/group12/GroupAssignment/Images/Icons/UWO_LOGO_TINY.png")); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -20, 160, 150));

        backgroundImage.setIcon(new javax.swing.ImageIcon("/Users/RexGu/Documents/UWO 2022-2023/CS2212/FInal Project/group12/GroupAssignment/Images/Icons/UWO.jpg")); // NOI18N
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void enterForgotUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterForgotUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterForgotUsernameActionPerformed

    private void enterNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterNewPasswordActionPerformed
    /**
     * The button go back to the login page
     * @param evt 
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LandingPage backLogin = new LandingPage();
        backLogin.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed
    /**
     * This method is save the new password
     * @param evt 
     */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (enterSecurityAnswer.getText().equals("2212") && selectSecurityQuestion.getSelectedItem().equals("Class Code")) {
            User user = this.searchUser();
            Admin admin = this.searchAdmin();
            if (enterForgotUsername.getText().equals("") || enterNewPassword.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Did you remember to press \"enter\" (Windows) or \"return\" (Mac)\nafter entering your password. This field has a null/blank value.");
                this.dispose();
                LandingPage refresh = new LandingPage();
                refresh.setVisible(true);
            } 
            
            if (user != null) {
                JOptionPane.showMessageDialog(this, "For user security purposes:\nUpon chaning passwords, (1)previous user favourites will be reset (2)and the account will need to select new favourites from the available maps.");
                usrDb.userRegister(enterForgotUsername.getText(), enterNewPassword.getText());
                this.dispose();
                LandingPage goback = new LandingPage();
                goback.setVisible(true);
            }
            else if (admin != null){
                JOptionPane.showMessageDialog(this, "For user security purposes:\nUpon chaning passwords, (1)previous user favourites will be reset (2)and the account will need to select new favourites from the available maps.");
                usrDb.adminRegister(enterForgotUsername.getText(), enterNewPassword.getText());
                this.dispose();
                LandingPage goback = new LandingPage();
                goback.setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(this, "Does not exists!\nSuggestion: Register a new account");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Incorrect security answer!");
            this.dispose();
            LandingPage backLogin = new LandingPage();
            backLogin.setVisible(true);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * Find the user in the database to see if the user is exists
     * @return 
     */
    private User searchUser() {  
        User user = null;
        String getUsername = enterForgotUsername.getText();
        System.out.println("Searching for username: "+ getUsername);
        User findUser = usrDb.getUser(getUsername); 
        System.out.println("Found: "+ findUser);
        if (findUser == null) {
            // do nothing
        }
        else {
            return findUser;
        }
        return findUser;
    }
    /**
     * Find the admin in the database to see if the admin is exists
     * @return 
     */
    private Admin searchAdmin() {  
        Admin admin = null;
        String getAdminName = enterForgotUsername.getText();
        System.out.println("Searching for username: "+ getAdminName);
        Admin findAdmin = usrDb.getAdmin(getAdminName); 
        System.out.println("Found: "+ findAdmin);
        if (findAdmin == null) {
            // do nothing
        }
        else {
            return findAdmin;
        }
        return findAdmin;
    }
    
    /**
     * Private method sets icons which includes Background video and logos.
     */
    private void setIcons(){
        backgroundImage.setIcon(new ImageIcon("Images/Icons/UWO.jpg"));
        Logo.setIcon(new ImageIcon("Images/Icons/UWO_LOGO_TINY.png"));
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JTextField enterForgotUsername;
    private javax.swing.JTextField enterNewPassword;
    private javax.swing.JTextField enterSecurityAnswer;
    private javax.swing.JLabel forgotSecurity;
    private javax.swing.JLabel forgotUsername;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> selectSecurityQuestion;
    // End of variables declaration//GEN-END:variables
}
