import org.json.simple.parser.JSONParser;
import java.io.*;
import org.json.simple.parser.ParseException;
import org.json.simple.JSONObject;
import org.json.simple.JSONArray;

public class OpeningPage extends javax.swing.JFrame {
    
    /*
    * Instance variables
    */
    
    User user;
    Admin admin;
    UserDatabase usrDb;
    SystemDatabase sysDb;
    String getUsername;
    String getPassword;
    JSONParser parser;

    /**
     * Creates new form LandingPage
     */
    public OpeningPage() {
        initComponents();
        this.parser = new JSONParser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDevelopers = new javax.swing.JLabel();
        labelTitle = new javax.swing.JLabel();
        labelGroup = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        videoBackground = new javax.swing.JLabel();
        safeImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDevelopers.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        labelDevelopers.setForeground(new java.awt.Color(255, 255, 255));
        labelDevelopers.setText("Developed by Hanyun, William, Xiaohui, Yangxiuye, and Taysean");
        getContentPane().add(labelDevelopers, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 670, 390, 20));

        labelTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("By Team 12");
        getContentPane().add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, -1, 20));

        labelGroup.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        labelGroup.setForeground(new java.awt.Color(255, 255, 255));
        labelGroup.setText("Western Geographic Information System");
        getContentPane().add(labelGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BROWSE MAPS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 210, 50));

        videoBackground.setIcon(new javax.swing.ImageIcon("/Users/tayseanwilson-nolan/NetBeansProjects/GroupAssignment/Images/Icons/UWO_DRONE.gif")); // NOI18N
        getContentPane().add(videoBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        safeImage.setIcon(new javax.swing.ImageIcon("/Users/tayseanwilson-nolan/NetBeansProjects/GroupAssignment/Images/Icons/UWO_2.jpg")); // NOI18N
        getContentPane().add(safeImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LandingPage loginPage = new LandingPage();
        loginPage.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelDevelopers;
    private javax.swing.JLabel labelGroup;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel safeImage;
    private javax.swing.JLabel videoBackground;
    // End of variables declaration//GEN-END:variables
}
